# Стандартные библиотеки и функции

# `os`

In [1]:
import os

In [3]:
# 'posix', 'nt', 'max', 'os2', 'ce', 'java'
os.name

'nt'

In [5]:
# Текущий id процесса
os.getpid()

25156

In [9]:
# Только в UNIX системах
os.uname()

AttributeError: module 'os' has no attribute 'uname'

In [ ]:
# Текущая директория
os.getcwd()

'e:\\Препод\\git\\Практика\\Практика - Основы Python'

In [ ]:
# Список файлов в текущей директории 
os.listdir()

['06112025_122730.json',
 'data.txt',
 'data_write.txt',
 'describe_pet.py',
 'HomeWork.ipynb',
 'Practice_1.ipynb',
 'Practice_modules.ipynb',
 'Practice_OOP.ipynb',
 '__pycache__',
 'Практика 1.md']

In [13]:
# Список файлов в директории 
os.listdir(f'E:\\Препод\\git')

['.git',
 '.gitignore',
 '.venv',
 'pyproject.toml',
 'README.md',
 'requirements.txt',
 'uv.lock',
 'Материалы',
 'Практика',
 'Семинары']

In [ ]:
print(f'До: {os.listdir()}')

# Создает папки по указанному пути
os.makedirs('./test')

print(f'После: {os.listdir()}')

До: ['06112025_122730.json', 'data.txt', 'data_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', '__pycache__', 'Практика 1.md']
После: ['06112025_122730.json', 'data.txt', 'data_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', 'test', '__pycache__', 'Практика 1.md']


In [17]:
print(f'До: {os.listdir()}')

# Удаляет файлы и папки по пути
os.removedirs('./test')

print(f'После: {os.listdir()}')

До: ['06112025_122730.json', 'data.txt', 'data_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', 'test', '__pycache__', 'Практика 1.md']
После: ['06112025_122730.json', 'data.txt', 'data_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', '__pycache__', 'Практика 1.md']


In [18]:
print(f'До: {os.listdir()}')

# Переименовывание файлов и папок
os.rename('./data_write.txt', './data_renamed_write.txt')

print(f'После: {os.listdir()}')

До: ['06112025_122730.json', 'data.txt', 'data_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', '__pycache__', 'Практика 1.md']
После: ['06112025_122730.json', 'data.txt', 'data_renamed_write.txt', 'describe_pet.py', 'HomeWork.ipynb', 'Practice_1.ipynb', 'Practice_modules.ipynb', 'Practice_OOP.ipynb', '__pycache__', 'Практика 1.md']


## `datetime`

In [19]:
from datetime import datetime

In [29]:
dt = datetime.today()

print(f'{dt}')
print(f'{dt.year} / {dt.month} / {dt.day}')
print(f'{dt.hour} : {dt.minute} : {dt.second}')
print(f'{dt.date()}')
print(f'{dt.time()}')

2025-12-03 19:18:00.562723
2025 / 12 / 3
19 : 18 : 0
2025-12-03
19:18:00.562723


In [ ]:
dt = datetime.now()
print(f'{dt}')

# Количество секунд считается с 01.01.1970
print(f'Секунд: {dt.timestamp()}') # 1_764_778_736.88042

2025-12-03 19:18:56.880420
Секунд: 1764778736.88042


In [33]:
print(f'{dt = }')

dt = datetime.datetime(2025, 12, 3, 19, 18, 56, 880420)


### Форматирование дат и времени

In [49]:
now = datetime.now()

temp = now.strftime('%d.%m.%Y')
print(f'{type(now)} -- {type(temp)}')

print(now.strftime('%d.%m.%Y'))
print(now.strftime('%d/%m/%y'))
print(now.strftime('%d - %m - %Y\n'))

print(now.strftime('%H:%M:%S'))
print(now.strftime('%d.%m.%Y %H:%M\n'))

print(now.strftime("%A, %d %B %Y"))
print(now.strftime("%a, %d %b %Y"))

<class 'datetime.datetime'> -- <class 'str'>
03.12.2025
03/12/25
03 - 12 - 2025

19:29:02
03.12.2025 19:29

Wednesday, 03 December 2025
Wed, 03 Dec 2025


In [50]:
date_str = "2025-12-31 23:59:59"

dt = datetime.strptime(date_str, '%Y-%m-%d %H:%M:%S')
print(f'{dt = }')
print(f'{type(dt) = }')

dt = datetime.datetime(2025, 12, 31, 23, 59, 59)
type(dt) = <class 'datetime.datetime'>


In [53]:
datetime.strptime("31/12/2025", "%d/%m/%Y"), \
datetime.strptime("Dec 31 2025", "%b %d %Y")

(datetime.datetime(2025, 12, 31, 0, 0), datetime.datetime(2025, 12, 31, 0, 0))

# `re`

### Специальные символы (метасимволы)

- `.`       Любой символ, кроме новой строки
- `^`       Начало строки
- `$`       Конец строки
- `*`       0 или более повторений
- `+`       1 или более повторений
- `?`       0 или 1 повторение
- `{m}`     Ровно m повторений
- `{m,n}`   От m до n повторений
- `[]`      Набор символов (любой из)
- `|`       ИЛИ (альтернатива)
- `()`      Группировка
- `\`       Экранирование специальных символов

- \d - соответствует любой одной цифре и заменяет собой выражение `[0-9]`;
- \D - исключает все цифры и заменяет `[^0-9]`;
- \w - заменяет любую цифру, букву, а также знак нижнего подчёркивания;
- \W - любой символ кроме латиницы, цифр или нижнего подчёркивания;
- \s - соответствует любому пробельному символу;
- \S - описывает любой непробельный символ;
- \b - граница слова.

In [2]:
r'\s+'

'\\s+'

In [4]:
import re

#### `re.match()`

In [ ]:
result = re.match(r'Это', 'Это вам не Это...')

In [7]:
result.group()

'Это'

In [8]:
result.start(), result.end()

(0, 3)

#### `re.search()`

In [12]:
result = re.search(r'вам ', 'Это вам не Это...')

In [15]:
result.group(), result.start(), result.end()

('вам ', 4, 8)

#### `re.findall()`

In [17]:
result = re.findall(r'Это', 'Это вам не Это...')
result

['Это', 'Это']

#### `re.split()`

In [19]:
result = re.split(r'е', 'Четырехсотпятидесятисемимиллиметровое')
print(f'{result = }')

result = ['Ч', 'тыр', 'хсотпятид', 'сятис', 'мимиллим', 'трово', '']


In [20]:
'Четырехсотпятидесятисемимиллиметровое'.split('e')

['Четырехсотпятидесятисемимиллиметровое']

#### `re.sub()`

In [24]:
result = re.sub(r'\s+', ' ', 'Текст   с    лишними    пробелами    и   знаками...  !')
print(f'{result = }')

result = 'Текст с лишними пробелами и знаками... !'


#### `re.compile()`

In [31]:
pattern = re.compile(r'\b[А-Я][а-я]*\b')
result = pattern.findall('это Вам нЕ ЭтО...')
result

['Вам']

In [37]:
pattern = re.compile(r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+$')
result = pattern.match('test@mailru')
print(f'{result}')

None


In [38]:
pattern = re.compile(r'\d\d/\d\d/\d{4}')
result = pattern.match('11/88/2025')
print(f'{result}')

<re.Match object; span=(0, 10), match='11/88/2025'>


In [40]:
pattern = re.compile(r'(?:\+7|8)(?:-\d{2,3}){4}')
result = pattern.match('+7-123-456-78-90')
print(f'{result}')

<re.Match object; span=(0, 16), match='+7-123-456-78-90'>


In [ ]:
pattern = re.compile(r'^(8|(\+7)) \d{3} \d{3}\-\d{2}\-\d{2}$')

# `NumPy`

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(f'{type(a) = }')
print(f'{a.shape = }')
print(f'{a.ndim = }')
print(f'{a[0], a[1], a[2]}')

type(a) = <class 'numpy.ndarray'>
a.shape = (3,)
a.ndim = 1
(np.int64(1), np.int64(2), np.int64(3))


In [47]:
a[0] = 5
print(a)

[5 2 3]


In [50]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print(f'{type(b) = }')
print(f'{b.shape = }')
print(f'{b.ndim = }')

[[1 2 3]
 [4 5 6]]
type(b) = <class 'numpy.ndarray'>
b.shape = (2, 3)
b.ndim = 2


In [51]:
b[0, 0], b[1, 1]

(np.int64(1), np.int64(5))

In [53]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [54]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [56]:
np.ones((3, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
np.full((5, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [60]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
rand_mat = np.random.random((2, 2))
rand_mat_int = np.random.randint(-100, 100, (3, 3))

print(rand_mat, '\n')
print(f'{rand_mat_int}')

[[0.46935974 0.25632979]
 [0.01973609 0.41490525]] 

[[ 19  68 -91]
 [-99 -16  86]
 [ 24 -52  48]]


In [74]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [76]:
temp = []
for i in range(10):
    temp.append(i ** 2)
temp

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [70]:
[i * 10 for i in range(10)]

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [93]:
vec = np.arange(10) ** 2
print(f'{vec}')

np.random.choice(vec, 3)

[ 0  1  4  9 16 25 36 49 64 81]


array([36, 25,  1])

In [95]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
print(a[0, 2])
print(a[0][2])

3
3


In [ ]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [100]:
print(a)
print(f'-----')
b[0, 0] = 77
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
